name: Update Whitelists

on:
  schedule:
    - cron: '0 */2 * * *'
  workflow_dispatch:

jobs:
  update-whitelists:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run whitelist generator
        run: node .

      - name: Run tests
        run: npm test

      - name: Pull latest changes
        run: git pull

      - name: Stage modified files
        run: git add .

      - name: Commit and push changes
        run: |
          git config user.name "Sefinek Actions"
          git config user.email "sefinek.actions@gmail.com"
          if [ -n "$(git status -s)" ]; then
            MODIFIED_FILES=$(git diff --name-only HEAD)
            FILE_COUNT=$(echo "$MODIFIED_FILES" | wc -l)
            if [ "$FILE_COUNT" -gt 0 ]; then
              git commit -am "Updated IP whitelists [$FILE_COUNT file(s)]" -m "$MODIFIED_FILES"
              git push origin main
            else
              echo "Canceled: No changes detected."
            fi
          else
            echo "Canceled: Nothing to commit."
          fi